name: Lint

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  go:
    name: Go formatting and linting
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod

      - name: Check Go formatting
        run: test -z "$(gofmt -l cmd internal)"

      - name: Lint Go
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          args: ./...
